create extension if not exists pg_trgm;

create index if not exists tasks_status_due_date_idx on public.tasks(status, due_date);
create index if not exists tasks_assignee_status_idx on public.tasks(assignee_id, status);
create index if not exists tasks_office_status_idx on public.tasks(office_id, status);
create index if not exists tasks_created_date_idx on public.tasks(created_date desc);
create index if not exists documents_office_status_date_idx on public.documents(office_id, status, date desc);
create index if not exists documents_author_date_idx on public.documents(author, date desc);
create index if not exists documents_updated_at_idx on public.documents(updated_at desc);
create index if not exists news_status_date_idx on public.news(status, date desc);
create index if not exists news_updated_at_idx on public.news(updated_at desc);
create index if not exists kb_articles_status_updated_at_idx on public.kb_articles(status, updated_at desc);
create index if not exists courses_status_updated_at_idx on public.courses(status, updated_at desc);
create index if not exists course_assignments_user_created_idx on public.course_assignments(user_id, created_at desc);
create index if not exists course_attempts_user_created_idx on public.course_attempts(user_id, created_at desc);
create index if not exists document_approvals_document_created_idx on public.document_approvals(document_id, created_at desc);
create index if not exists notifications_recipient_created_idx on public.notifications(recipient_user_id, created_at desc);
create index if not exists notifications_recipient_unread_idx on public.notifications(recipient_user_id, is_read, created_at desc);
create index if not exists lms_courses_status_updated_at_idx on public.lms_courses(status, updated_at desc);
create index if not exists lms_subsection_progress_user_updated_idx on public.lms_subsection_progress(user_id, updated_at desc);
create index if not exists lms_course_assignments_user_created_idx on public.lms_course_assignments(user_id, created_at desc);
create index if not exists audit_log_actor_created_idx on public.audit_log(actor_user_id, created_at desc);
create index if not exists audit_log_entity_created_idx on public.audit_log(entity_type, created_at desc);
create index if not exists report_delivery_schedules_active_next_run_idx on public.report_delivery_schedules(is_active, next_run_at);
create index if not exists report_delivery_runs_recipient_generated_idx on public.report_delivery_runs(recipient_user_id, generated_at desc);
create index if not exists documents_title_trgm_idx on public.documents using gin (title gin_trgm_ops);
create index if not exists documents_body_trgm_idx on public.documents using gin (coalesce(body, '') gin_trgm_ops);
create index if not exists kb_articles_title_trgm_idx on public.kb_articles using gin (title gin_trgm_ops);
create index if not exists kb_articles_content_trgm_idx on public.kb_articles using gin (content gin_trgm_ops);
create index if not exists lms_courses_title_trgm_idx on public.lms_courses using gin (title gin_trgm_ops);
create index if not exists lms_courses_description_trgm_idx on public.lms_courses using gin (coalesce(description, '') gin_trgm_ops);
create index if not exists lms_subsections_markdown_trgm_idx on public.lms_subsections using gin (markdown_content gin_trgm_ops);
